version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - ELASTICACHE_ENDPOINT=redis:6379
      - DJANGO_SETTINGS_MODULE=a_core.settings
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web_nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8001:81"
    depends_on:
      - web
volumes:
  static_volume:


