services:
  django: 
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    container_name: web
    command: /start.sh
    environment:
      - ELASTICACHE_ENDPOINT=redis:6379
  redis:
    image: redis:alpine
    expose:
        - 6379
