"""
Django settings for a_core project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import socket

from .settings import *
from .settings import env

DEBUG = False

ALLOWED_HOSTS = ["*"]
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
ALLOWED_HOSTS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]

AWS_S3_CUSTOM_DOMAIN = "images.keeplist.io"

AWS_BUCKET = {
    "bucket_name": env.str("AWS_STORAGE_BUCKET_NAME"),
    "custom_domain": AWS_S3_CUSTOM_DOMAIN,
    "querystring_auth": False,
    "file_overwrite": False
}

STORAGES = {
    "default": {"BACKEND": "storages.backends.s3.S3Storage", "OPTIONS": AWS_BUCKET},
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            **AWS_BUCKET,
            "file_overwrite": True,
            "location": "web_static",
        },
    },
}

STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/web_static/"
# MEDIA
# ------------------------------------------------------------------------------
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

INSTALLED_APPS += ["storages"]  # noqa: F405


INTERNAL_IPS = [
    "127.0.0.1",
]

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": True,
#     "formatters": {
#         "verbose": {
#             "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s",
#         },
#     },
#     "handlers": {
#         "console": {
#             "level": "DEBUG",
#             "class": "logging.StreamHandler",
#             "formatter": "verbose",
#         }
#     },
#     "root": {"level": "INFO", "handlers": ["console"]},
#     "loggers": {
#         "django.db.backends": {
#             "level": "ERROR",
#             "handlers": ["console"],
#             "propagate": False,
#         },
#         # Errors logged by the SDK itself
#         "sentry_sdk": {"level": "ERROR", "handlers": ["console"], "propagate": False},
#         "django.security.DisallowedHost": {
#             "level": "ERROR",
#             "handlers": ["console"],
#             "propagate": False,
#         },
#     },
# }
